-- Added per Kathy's email Dated 4/2/2020 @ 2:17pm Servcie Items Response

insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT1','SLP-HP-WITH MAINTENANCE')
insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT1-347','SLP-HP-WITH MAINTENANCE')
insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT2','SLP-HP-WITH MAINTENANCE')
insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT3','SLP-HP-WITH MAINTENANCE')
insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT4','SLP-HP-WITH MAINTENANCE')
insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT5','SLP-HP-WITH MAINTENANCE')
insert into ITEMCODE_MAS_NS (MAS,NETSUITE) VALUES('XAT6','SLP-HP-WITH MAINTENANCE')
