USE [babblefish]
GO

/****** Object:  Table [dbo].[AR_Customer]    Script Date: 3/31/2020 12:28:06 PM ******/
DROP TABLE [dbo].[AR_Customer]
GO

/****** Object:  Table [dbo].[AR_Customer]    Script Date: 3/31/2020 12:28:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AR_Customer](
	[ARDivisionNo] [nvarchar](255) NULL,
	[CustomerNo] [nvarchar](255) ,
	[CustomerName] [nvarchar](255) NULL,
	[AddressLine1] [nvarchar](255) NULL,
	[AddressLine2] [nvarchar](255) NULL,
	[AddressLine3] [nvarchar](255) NULL,
	[City] [nvarchar](255) NULL,
	[State] [nvarchar](255) NULL,
	[ZipCode] [nvarchar](255) NULL,
	[CountryCode] [nvarchar](255) NULL,
	[TelephoneNo] [nvarchar](255) NULL,
	[TelephoneExt] [nvarchar](255) NULL,
	[FaxNo] [nvarchar](255) NULL,
	[EmailAddress] [nvarchar](255) NULL,
	[URLAddress] [nvarchar](255) NULL,
	[EBMEnabled] [nvarchar](255) NULL,
	[EBMConsumerUserID] [nvarchar](255) NULL,
	[BatchFax] [nvarchar](255) NULL,
	[DefaultCreditCardPmtType] [nvarchar](255) NULL,
	[ContactCode] [nvarchar](255) NULL,
	[ShipMethod] [nvarchar](255) NULL,
	[TaxSchedule] [nvarchar](255) NULL,
	[TaxExemptNo] [nvarchar](255) NULL,
	[TermsCode] [nvarchar](255) NULL,
	[SalespersonDivisionNo] [nvarchar](255) NULL,
	[SalespersonNo] [nvarchar](255) NULL,
	[Comment] [nvarchar](255) NULL,
	[SortField] [nvarchar](255) NULL,
	[TemporaryCustomer] [nvarchar](255) NULL,
	[OpenItemCustomer] [nvarchar](255) NULL,
	[ResidentialAddress] [nvarchar](255) NULL,
	[StatementCycle] [nvarchar](255) NULL,
	[PrintDunningMessage] [nvarchar](255) NULL,
	[CustomerType] [nvarchar](255) NULL,
	[PriceLevel] [nvarchar](255) NULL,
	[DateLastActivity] [datetime] NULL,
	[DateLastPayment] [datetime] NULL,
	[DateLastStatement] [datetime] NULL,
	[DateLastFinanceChrg] [datetime] NULL,
	[DateLastAging] [datetime] NULL,
	[DefaultItemCode] [nvarchar](255) NULL,
	[CreditHold] [nvarchar](255) NULL,
	[PrimaryShipToCode] [nvarchar](255) NULL,
	[DateEstablished] [datetime] NULL,
	[DefaultPaymentType] [nvarchar](255) NULL,
	[EmailStatements] [nvarchar](255) NULL,
	[NumberOfInvToUseInCalc] [float] NULL,
	[AvgDaysPaymentInvoice] [float] NULL,
	[AvgDaysOverDue] [float] NULL,
	[CustomerDiscountRate] [float] NULL,
	[ServiceChargeRate] [float] NULL,
	[CreditLimit] [float] NULL,
	[LastPaymentAmt] [float] NULL,
	[HighestStmntBalance] [float] NULL,
	[UnpaidServiceChrg] [float] NULL,
	[BalanceForward] [float] NULL,
	[CurrentBalance] [float] NULL,
	[AgingCategory1] [float] NULL,
	[AgingCategory2] [float] NULL,
	[AgingCategory3] [float] NULL,
	[AgingCategory4] [float] NULL,
	[OpenOrderAmt] [float] NULL,
	[RetentionCurrent] [float] NULL,
	[RetentionAging1] [float] NULL,
	[RetentionAging2] [float] NULL,
	[RetentionAging3] [float] NULL,
	[RetentionAging4] [float] NULL,
	[DateCreated] [datetime] NULL,
	[TimeCreated] [nvarchar](255) NULL,
	[UserCreatedKey] [nvarchar](255) NULL,
	[DateUpdated] [datetime] NULL,
	[TimeUpdated] [nvarchar](255) NULL,
	[UserUpdatedKey] [nvarchar](255) NULL,
	[UDF_LEAD_SOURCE] [nvarchar](255) NULL,
	[UDF_SLXID] [nvarchar](255) NULL,
	[UDF_BWID] [nvarchar](255) NULL,
	[UDF_CCNUMBER] [nvarchar](255) NULL,
	[SalespersonDivisionNo2] [nvarchar](255) NULL,
	[SalespersonNo2] [nvarchar](255) NULL,
	[SalespersonDivisionNo3] [nvarchar](255) NULL,
	[SalespersonNo3] [nvarchar](255) NULL,
	[SalespersonDivisionNo4] [nvarchar](255) NULL,
	[SalespersonNo4] [nvarchar](255) NULL,
	[SalespersonDivisionNo5] [nvarchar](255) NULL,
	[SalespersonNo5] [nvarchar](255) NULL,
	[DefaultCostCode] [nvarchar](255) NULL,
	[DefaultCostType] [nvarchar](255) NULL,
	[SplitCommRate2] [float] NULL,
	[SplitCommRate3] [float] NULL,
	[SplitCommRate4] [float] NULL,
	[SplitCommRate5] [float] NULL,
	[CustomerStatus] [nvarchar](255) NULL,
	[InactiveReasonCode] [nvarchar](255) NULL,
	[CreditCardGUID] [nvarchar](255) NULL,
	[UseSageCloudForInvPrinting] [nvarchar](255) NULL
) ON [PRIMARY]
GO


