/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [externalid]
      ,[otherrefnum]
      ,[vendor]
      ,[purchasecontract]
      ,[Employee]
      ,[supervisorapproval]
      ,[duedate]
      ,[trandate]
      ,[tranId]
      ,[memo]
      ,[department]
      ,[class]
      ,[location]
      ,[custbody_nsts_gaw_tran_requestor]
      ,[exchangeRate]
      ,[purchaseItemLine_item]
      ,[purchaseItemLine_quantity]
      ,[purchaseItemLine_serialNumbers]
      ,[purchaseItemLine_units]
      ,[purchaseItemLine_rate]
      ,[purchaseItemLine_amount]
      ,[purchaseItemLine_description]
      ,[purchaseItemLine_department]
      ,[purchaseItemLine_class]
      ,[purchaseItemLine_location]
      ,[purchaseItemLine_customer]
      ,[purchaseItemLine_isBillable]
      ,[purchaseItemLine_isClosed]
      ,[itemLine_custom:Field Name]
      ,[itemLine_custom:Field Name1]
      ,[terms]
      ,[billaddresslist]
      ,[billAttention]
      ,[billAddressee]
      ,[billAddr1]
      ,[billAddr2]
      ,[billCity]
      ,[billState]
      ,[billZip]
      ,[billCountry]
      ,[billPhone]
      ,[ toBePrinted]
      ,[toBeEmailed]
      ,[email]
      ,[toBeFaxed]
      ,[fax]
      ,[vendorMessage]
      ,[custom:Field Name1]
      ,[custom:Field Name2]
      ,[custom:Field Name3]
  FROM [babblefish].[dbo].[PurchaseOrderTemplate]