/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Inactive]
      ,[Name]
      ,[Display Name]
      ,[Vendor]
      ,[Type]
      ,[Description]
      ,[MAS Vendor Code]
      ,[Base Price]
      ,[External ID]
      ,[Internal ID]
      ,[Purchase Price]
      ,[Vendor Code]
      ,[Id]
  FROM [babblefish].[dbo].[Items]